[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="menu" type="java.lang.String" --]
[#-- @ftlvariable name="users" type="ru.itmo.web.lesson4.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.lesson4.model.User" --]
[#-- @ftlvariable name="user_id" type="java.lang.Long" --]
[#-- @ftlvariable name="posts" type="ru.itmo.web.lesson4.model.Post[]" --]
[#-- @ftlvariable name="post" type="ru.itmo.web.lesson4.model.Post" --]
